add desktop nav
profcomff/toolbar-element pull request #2
Opened 2023-02-03 22:29 UTC by physphile

2023-02-03 22:42 UTC, grigoriev-semyon approved these changes

2023-02-04 09:34 UTC, dyakovri requested changes

2023-02-04 09:34 UTC, dyakovri commented on src/components/ToolbarBack.vue
> +    </div>
Может их в компонент вынести?

2023-02-04 09:34 UTC, dyakovri commented on src/mixins/captureNavigation.js
> +            }
Может заменить try/except на .then().catch(), чтобы поток не блочить?

2023-02-04 11:53 UTC, physphile commented on src/mixins/captureNavigation.js
> +            }
`fetch` возвращает промис, который мы никак не обрабатываем, поэтому `try catch` тут не нужны. Здесь просто в моменте отправляется запрос на сервис, поток не блочится

2023-02-04 11:59 UTC, dyakovri commented on src/mixins/captureNavigation.js
> +            }
Окей, буду знать
Но тогда зачем ты вообще его оставил? 😂

2023-02-04 12:08 UTC, physphile commented on src/mixins/captureNavigation.js
> +            }
я другое поправлял, не обратил внимания

2023-02-04 12:10 UTC, physphile commented on src/components/ToolbarBack.vue
> +    </div>
ну я же быстренько поправлял) Я вообще хочу нормально написать хедер, чтобы менять пропсы, а не варианты

2023-02-04 12:47 UTC, dyakovri approved these changes

2023-02-04 17:29 UTC, merged